### ISSUE TITLE
Automatic shutdown at specific time.

### ISSUE THREAD

**Issue by milindhvijay** [quintus-lab/OpenWRT-Rockchip#16]
Kernel 5.10 version 21.02 for nanopi r2s shutting down everyday at 4 AM IST/2:30 PM PST. RJ45 lights blink on both WAN and LAN but device led does not work. LuCi does not open. Need to replug to get it working.

**Comment by quintus-lab** [comment]
The coremark that runs a scheduled task a 4 AM, it would causes the device run at maxiumu power.
If the microusb power supply don't have enough power, it can cause system crash & reboot.

workaround:
remove coremark scheduled task on LuCI: system-Scheduled Tasks.
