### ISSUE TITLE
A few things not working

### ISSUE THREAD

**Issue by dallascaudell** [quintus-lab/OpenWRT-Rockchip#17]
I have the 1GB edition running the 5.10 - 4/15/21 and a few things aren't working. I'm really new to openwrt and have a little experience with linux/ubuntu. 

cpufreq
AdByBy
ZeroTier

These processes will not run, even after trying to configure the second two.

**Comment by quintus-lab** [comment]
Some files permissions need to add with +x  and have been fixed, pls try again.
