### ISSUE TITLE
Router keeps pinging random websites

### ISSUE THREAD

**Issue by milindhvijay** [quintus-lab/OpenWRT-Rockchip#19]
The router keeps pinging a random set of websites every minute. My devices don't ping openwrt for dns. I have something similar to pihole and can see this happening every minute.
![Screenshot (6)](https://user-images.githubusercontent.com/22214967/115977406-8d0bc100-a595-11eb-9bf5-da15cf424002.png)
![Screenshot (1)](https://user-images.githubusercontent.com/22214967/115977408-8ed58480-a595-11eb-829b-0b5aed9a2f5a.png)
![Screenshot (3)](https://user-images.githubusercontent.com/22214967/115977409-8f6e1b00-a595-11eb-8659-689b01676e3a.png)
![Screenshot (4)](https://user-images.githubusercontent.com/22214967/115977410-9006b180-a595-11eb-8def-c54137ae924d.png)
![Screenshot (5)](https://user-images.githubusercontent.com/22214967/115977412-9006b180-a595-11eb-98a6-11ece6f4707e.png)

**Comment by 53c70r** [comment]
Maybe it is one of the preinstalled services.
just a guess.

**Comment by quintus-lab** [comment]
It seems that has some services keeping  check some DNS list, but I didn't find any on OpenWrt.
Can you  leave the OpenWrt alone to  uplink to pihole for a  check?
