### ISSUE TITLE
Request: igmpproxy support

### ISSUE THREAD

**Issue by happy201807** [quintus-lab/OpenWRT-Rockchip#20]
Is it possible to add igmpproxy  (igmpproxy) support for IPTV multicast streaming into the r4s builds？

**Comment by quintus-lab** [comment]
opkg update
opkg install igmpproxy
Please refer to :
[IPTV / UDP multicast](https://openwrt.org/docs/guide-user/network/wan/udp_multicast)

**Comment by happy201807** [comment]
Can you integrate into the r4s release board by default?

**Comment by quintus-lab** [comment]
> Can you integrate into the r4s release board by default?

Let me try to do a test for that.

**Comment by happy201807** [comment]
> > Can you integrate into the r4s release board by default?
> 
> Let me try to do a test for that.

Thank you, if you need to test the r4s-related version, I can assist you.

**Comment by quintus-lab** [comment]
> > > Can you integrate into the r4s release board by default?
> > 
> > 
> > Let me try to do a test for that.
> 
> Thank you, if you need to test the r4s-related version, I can assist you.

pls download & try
[r4s-for-igmproxy](https://github.com/quintus-lab/OpenWRT-Rockchip/releases/download/2102/r4s-for-igmproxy-ext4.zip)

**Comment by happy201807** [comment]
> > > > Can you integrate into the r4s release board by default?
> > > 
> > > 
> > > Let me try to do a test for that.
> > 
> > 
> > Thank you, if you need to test the r4s-related version, I can assist you.
> 
> pls download & try
> [r4s-for-igmproxy](https://github.com/quintus-lab/OpenWRT-Rockchip/releases/download/2102/r4s-for-igmproxy-ext4.zip)

Can you provide this file type "nanopi-r4s-squashfs-sysupgrade.img.gz"? I'm not sure if ext4 is compatible.

**Comment by quintus-lab** [comment]
> > > > > Can you integrate into the r4s release board by default?
> 
> > > > 
> 
> > > > 
> 
> > > > Let me try to do a test for that.
> 
> > > 
> 
> > > 
> 
> > > Thank you, if you need to test the r4s-related version, I can assist you.
> 
> > 
> 
> > pls download & try
> 
> > [r4s-for-igmproxy](https://github.com/quintus-lab/OpenWRT-Rockchip/releases/download/2102/r4s-for-igmproxy-ext4.zip)
> 
> 
> 
> Can you provide this file type "nanopi-r4s-squashfs-sysupgrade.img.gz"? I'm not sure if ext4 is compatible.

In my opinion, SFS is not a good idea on TF card because overlay is not stable enough.


https://github.com/quintus-lab/OpenWRT-Rockchip/releases/download/2102/r4s-for-igmproxy-sfs.zip

**Comment by happy201807** [comment]
It's ok.

**Comment by happy201807** [comment]
Can you add igmpproxy to the seeds of stable branches such as 21.02 by default?
