### ISSUE TITLE
the network tunnel mode of helloworld

### ISSUE THREAD

**Issue by happy201807** [quintus-lab/OpenWRT-Rockchip#21]
Hi, I tried to divert the traffic of the wg0 interface based on helloworld, but it doesn't seem to work. What is wrong?server config is as follows:

   ```config servers
	option switch_enable '0'
	option type 'tun'
	option iface 'wg0'
	option local_port '1234'
	option alias 'WG0'
	option ip 'Usage:'
   ```

**Comment by quintus-lab** [comment]
sorry, i have no idea for that.
