### ISSUE TITLE
How to flash

### ISSUE THREAD

**Issue by jurijzahn8019** [quintus-lab/OpenWRT-Rockchip#24]
Hi 

i have downloaded the [image](https://github.com/quintus-lab/OpenWRT-Rockchip/releases/download/release/R1-plus-QC-2021-05-23-2102.zip) and flashed it. 

But my OrangePi R1 Plus doesn't boot.  The Red led flashes one time and then it is dead.

The Image from [OrangePi](http://www.orangepi.org/downloadresources/orangepiR1Plus/2020-12-22/orangepiR1357b4fd6e8b12f7bc81d7e40e7.html) works.

Am i doing something wrong?

I also tried to update via LuCI (via upload the openwrt-rockchip-armv8-xunlong_orangepi-r1-plus-ext4-sysupgrade.img.gz) 
But it has bricked the device.

Any  help is appreciated

Thanks

**Comment by jurijzahn8019** [comment]
![IMG_20210608_203829](https://user-images.githubusercontent.com/44019949/121239489-988f1f00-c899-11eb-8255-e2d6e83c8749.jpg)


This my device

**Comment by quintus-lab** [comment]
Can you try another TF card?
I've tested that it works normally

**Comment by jurijzahn8019** [comment]
Just tested in another card. Unfortunately it didn't  work. 

BTW: I am using Balena Etcher. Should i use something else?

**Comment by jurijzahn8019** [comment]
Tried

```bash
sudo dd if=./openwrt-rockchip-armv8-xunlong_orangepi-r1-plus-ext4-sysupgrade.img of=/dev/sdg bs=16K
```
without success

**Comment by jurijzahn8019** [comment]
Ok. Thanks! I will try again. Maybe I will figure it out.

**Comment by kevingdon** [comment]
@jurijzahn8019 Did you ever figure this out? I am having the exact same symptom (red light on for one second, then nothing) on the three images I tried from here (snapshot 9/5, 21.02 9/5, 21.02 8/27). The images I built from https://github.com/nebulakl/openwrt boot up fine, so I know the board and sdcard function (sometimes at least).

**Comment by jurijzahn8019** [comment]
Sorry, but I did not. 
I am building from nebulaki's repo too. It works fine.
