### ISSUE TITLE
ipv6 is not detected on the internet

### ISSUE THREAD

**Issue by jebuenga** [quintus-lab/OpenWRT-Rockchip#26]
ipv6 address is not detected on the internet. when pinging google, or checking the ipv6 address for example in https://test-ipv6.com/ it says there's no ipv6 address.

wan6 and lan on the other hand have ipv6 addresses and dhcpv6 assignments are showing in the status page.

I'm using the release file **R4S-QC-2021-06-19-2102.zip**

**Comment by quintus-lab** [comment]
Something is missing and will be fixed in the next version.
workaround under the terminal console:
uci set dhcp.@dnsmasq[0].filteraaaa=0
uci commit

**Comment by quintus-lab** [comment]
The AAAA filter option has been fixed in the new version.
