### ISSUE TITLE
Lan IP address changing after reboot

### ISSUE THREAD

**Issue by milindhvijay** [quintus-lab/OpenWRT-Rockchip#27]
Not able to change LAN address. Defaults back to 192.168.1.1 after reboot

**Comment by quintus-lab** [comment]
It's probably TF card filesystem read only, rewrite or get another TF card try again.

**Comment by milindhvijay** [comment]
Tried it. Still the same. Had to downgrade to Quintus Build@2021.06.18

**Comment by milindhvijay** [comment]
Any Suggestions?
