### ISSUE TITLE
Some of the plugins don't have execute permission

### ISSUE THREAD

**Issue by jebuenga** [quintus-lab/OpenWRT-Rockchip#28]
Using `06-29-2021` and later builds, if you go to `/etc/init.d` and list down all files in the directory, there will be some apps that don't have execute permission. Because of this, these plugins don't work. For example, `cpufreq`, the frequencies governor when set in luci will not work. Another is `adbyby+`, it will fail to start.

The workaround to this is adding `+x` to the files, however the installation of this plugins might be broken so its dependencies might have an issue. Are you able to make a new build which fixes the installation/permission of the plugins?

**Comment by quintus-lab** [comment]
Done, thanks for your feedback.
